### ISSUE TITLE
helptu run evilginx

### ISSUE THREAD

**Issue by tutanota** [hash3liZer/phishlets#14]
you know why this error happens

Acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

**Comment by horllste** [comment]
try it again

**Comment by micahunder** [comment]
same error here

**Comment by horllste** [comment]
Are you certain you configure your DNS perfectly?

**Comment by tutanota** [comment]
yes I follow all intrutions  
my icq is @evilslam


Feb 25, 2020, 07:32 by notifications@github.com:

**Comment by horllste** [comment]
okay

**Comment by MikeTrust** [comment]
send me a mail and I will solve your issues (miketrust608@gmail.com)

**Comment by abampalexnder** [comment]
I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue 

any one need solution can contact on wire @abampalxender
19 Apr 2020
