### ISSUE TITLE
I see this error 

### ISSUE THREAD

**Issue by tutanota** [hash3liZer/phishlets#15]
[err] failed to load phishlet 'razer.yaml': force_post: unknown type - only 'post' is currently supported
commenting on other things
I have seen that many have this error
ACMEV2 UPDATE / ERROR 403

but I do not see anyone help I saw this error in your configuration phishlets but although I do not even know which page is that reason I notify you so you know.
I thought that the evilginx could also include an improvement to include javascript injection I don't know if it can already be done I don't know anything about programming in golang or in javascript but they could link to beef framework for other utilities or functions

**Comment by ghost** [comment]
if you can drop contact, i should be able to look into it and resolve issue over anydesk.

**Comment by tutanota** [comment]
How do you suggest you tell me, I would really appreciate it

**Comment by tutanota** [comment]
trabajos@tutanota.com

**Comment by tutanota** [comment]
the anydesk looks bad the teamviewer is the one I see that works let me know, thanks


Feb 22, 2020, 11:35 by notifications@github.com:

**Comment by tutanota** [comment]
hash3liZer isend you a msg to icq

**Comment by horllste** [comment]
> hash3liZer isend you a msg to icq

what error are you seeing?

**Comment by tutanota** [comment]
> > hash3liZer isend you a msg to icq
> 
> what error are you seeing?

Acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

**Comment by horllste** [comment]
did you have teamviewer?

**Comment by tutanota** [comment]
1556131778
2r94vq


Feb 25, 2020, 14:54 by notifications@github.com:

**Comment by horllste** [comment]
lol..
what is your email?
