### ISSUE TITLE
facebook phishlets

### ISSUE THREAD

**Issue by pretech86** [hash3liZer/phishlets#22]
i used evilginx facebook phishlet and i successfully generated the certificate but it return an encrypted password 

![evilginx2](https://user-images.githubusercontent.com/46816468/81286656-1155f300-906a-11ea-8680-ab9932c38316.jpg)

![evilginx1](https://user-images.githubusercontent.com/46816468/81286648-1024c600-906a-11ea-941f-ff69dd66bdb9.jpg)

any one can help me

**Comment by An0nUD4Y** [comment]
@pretech86 , Let me see it.
Message me on telegram ... https://t.me/its_udy

**Comment by An0nUD4Y** [comment]
@pretech86 , 
Check Here I have pushed the fixed phishlet.
https://github.com/An0nUD4Y/Evilginx2-Phishlets

**Comment by hash3liZer** [comment]
@An0nUD4Y You can't advertise here. So, i am removing your comments.

**Comment by hash3liZer** [comment]
@pretech86 Hi, this issue is generated from the credentials section. Check your credentials settings in the phishlet.

**Comment by Sphinx157** [comment]
Did you fix?
