### ISSUE TITLE
Google Phishlet - Nothing Append After "Continue" Button

### ISSUE THREAD

**Issue by charlesbel** [hash3liZer/phishlets#23]
Hi,
First, I would like to say Awesome thanks to hash3liZer for his work!
So I open this issue today because when I tested the Google phishlet, I opened the login page but when I entered the email, I clicked on "Continue" button to enter my password on the next page but nothing append on the click.
In the network tab, I can see an error just after the click on a request to my own servers.
I saw that some others issues are opened on the same subject but I understood that nobody found the issue...
So anyone avec any update about that ?
Sincerely

**Comment by An0nUD4Y** [comment]
@charlesbel ...
Try My collected/Created phishlets Here https://github.com/An0nUD4Y/Evilginx2-Phishlets

**Comment by charlesbel** [comment]
@An0nUD4Y 
I tried your phishlets but on the google one, there is a lot of not successful requests to play.google.com
[See image here](https://i.imgur.com/zJqDHP3.png)
When I click on the next button after the entering my email, google show me an error like : unable to connect, this browser is not secure
[See image here](https://i.imgur.com/p51OxuO.png)

**Comment by pretech86** [comment]
@An0nUD4Y i can’t find your phishlets

**Comment by mako007** [comment]
@charlesbel same issues experienced, blockchain phishlet too doesn't work, thanks

**Comment by hash3liZer** [comment]
Google has built-in javascript protection against the framework. You can check more thoroughly by studying the request payload sent when the continue button is pressed. As for now, i'll close the issue.

**Comment by hash3liZer** [comment]
@mako007 Hi, Blockchain recently integrated new protection against proxy attacks.
