### ISSUE TITLE
load the new phishlets

### ISSUE THREAD

**Issue by pkyc** [hash3liZer/phishlets#25]
Hi, 

I am using Evilginx  version 2.3.0.  After place the new phishlet file (e.g. yahoo.yaml) under the phishlets directory, run the evilginx again. Enter phishnets, but the new phishlets not shown in the table.  Do I need to rebuild the evilginx or some config missing?

thx...peter

**Comment by roymillar** [comment]
i think what you should type is "phishlets" without the quote.
from the issue you stated up you said you " enter phishnets" but it should be phishlets so that it can list them .

**Comment by horllste** [comment]
make
make install

**Comment by hash3liZer** [comment]
Everything's fine. Just supply `-p` argument along with evilginx2 command: 
```
$ ./main -p phishlets_directory/
```
