### ISSUE TITLE
error in google phishlet

### ISSUE THREAD

**Issue by gillufarooq** [hash3liZer/phishlets#7]
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure . I got this error in google phishlet i think google updated their policy ,any updates related to this issue?
![Capture](https://user-images.githubusercontent.com/55867369/65761484-4bf0c800-e138-11e9-996c-e58294e40cb0.PNG)

**Comment by sk3lk0** [comment]
yea i have this problem too, are you fixed that?

**Comment by hash3liZer** [comment]
This issue is related to google itself not of phishlet.
