### ISSUE TITLE
Google phishlet error

### ISSUE THREAD

**Issue by Incognito00** [hash3liZer/phishlets#9]
Go to link error appears 
![2019-11-01_0340](https://user-images.githubusercontent.com/53401121/67994085-748a4700-fc3b-11e9-8bcf-bdb2b47919cf.png)
Help!

**Comment by JSheadache** [comment]
I am testing with a similar setup and am stuck with error:
"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.”

If you are still working on this and want to compare notes, please drop me a line at zoomdeveloper@protonmail.com.

**Comment by arinze12345** [comment]
> Go to link error appears
> ![2019-11-01_0340](https://user-images.githubusercontent.com/53401121/67994085-748a4700-fc3b-11e9-8bcf-bdb2b47919cf.png)
> Help!



i can update it for you..bro...message me 
rickorkins@gmail.com
ICQ=@rickbaba

**Comment by arcticmunkii** [comment]
Any update on this? Apparently this is just a dead end now. Are there any working iCloud or Google phishlets?

**Comment by arinze12345** [comment]
Yes there is...a friend of mine has Google phishlet but sells it cost...
while I have asked him...why he's own works and mine is not working,,he
said it's from evilginx2 and not from the phishlet itself...

**Comment by hash3liZer** [comment]
Yes, we can make both the Gmail & iCloud phishlets work. There are always workarounds. However, in both cases, the only thing you would miss out is cookies. The rest can still happen.

**Comment by arcticmunkii** [comment]
Perfect, thanks for the update. As of this second are they working? If not, who's the best person to contact regarding this?

Forgive me for asking but aren't they pointless phishlets if we don't get the session cookies? How else would we gain access? 

Thanks in advance.

If you have any more info on where I can learn more myself, I'd be very greatful.

**Comment by hash3liZer** [comment]
The gmail and icloud phishlets, both are outdated. Due to lack of time, i wasn't able to update them. Because, they need to be continuously updated as both the tech giants keep changing site from time to time. And yes or no, maybe. Because some site needs more than just credentials to login. And some simply need credentials. So, it really depends what you are targetting.

**Comment by hash3liZer** [comment]
Will be closing this issue in next few hours.

**Comment by arcticmunkii** [comment]
Where is the best place I can contact you regarding a few question from a fellow learner? Thanks.

**Comment by hash3liZer** [comment]
On email: admin@shellvoide.com
